name: 'Get cache dependencies'
description: 'Get dependencies (via npm) and cache them'
input:
    caching: 
        description: 'wether to cache dependencies or not.'
        required: false
        default: 'true'
output:
    used-cases:
        description: 'wether the cache was used.'
        value: ${{ steps.install.output.cache }}
run: 
    using: 'composite'
    steps:
        - name: Cache dependencies
          if: inputs.caching == 'true'
          id: cache
          uses: actions/cache@v3
          with:
            path: node_modules
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
        - name: Install dependencies
          id: install
          if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
          run: |
            npm ci
            echo "::set-output name=cache:: ${{ inpur.cacheing }}"
          shell: bash