AWSTemplateFormatVersion: "2010-09-09"
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket to create.
    Default: my-demo-s3-bucket-test-project-11
