AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      BucketPolicy:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: AllowFullAccess
              Effect: Allow
              Principal: "*"
              Action: "s3:*"
              Resource:
                - !Sub 'arn:aws:s3:::${BucketName}'
                - !Sub 'arn:aws:s3:::${BucketName}/*'

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket to create
