AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: 'ami-0c55b159cbfafe1f0'
      Tags:
        - Key: Name
          Value: !Ref EC2InstanceName

Outputs:
  InstanceId:
    Description: 'The ID of the EC2 instance'
    Value: !Ref EC2Instance
