AWSTemplateFormatVersion: "2010-09-09"

Resources:
  EC2ExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "EC2ExecutionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "s3:GetObject"
                Resource: "*"

Outputs:
  EC2ExecutionRoleArn:
    Description: "ARN of the EC2 execution role"
    Value: !GetAtt EC2ExecutionRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-EC2ExecutionRoleArn"
