AWSTemplateFormatVersion: '2010-09-09'
Description: >
  IAM roles for resources.

Resources:

  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: IAMRole.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: IAMRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: "*"
        - PolicyName: AdditionalPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:StartInstances
                  - ec2:StopInstances
                  - ec2:TerminateInstances
                  - ec2:RebootInstances
                Resource: "*"

Outputs:
  IAMRole:
    Description: "ARN of the IAM Role"
    Value: !GetAtt IAMRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-IAMRoleArn"
