AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  LambdaCodeBucket:
    Type: String
    Description: "S3 bucket where Lambda code is stored"

  LambdaCodeKey:
    Type: String
    Description: "S3 key where Lambda code is stored"

  LambdaExecutionRoleArn:
    Type: String
    Description: "ARN of the IAM role that Lambda functions will use"

  LambdaFunctionName1:
    Type: String
    Description: "The name of the first Lambda function"

  LambdaFunctionName2:
    Type: String
    Description: "The name of the second Lambda function"

  LambdaFunctionName3:
    Type: String
    Description: "The name of the third Lambda function"

Resources:
  LambdaFunction1:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: !Ref LambdaFunctionName1
      Handler: "index.handler"
      Role: !Ref LambdaExecutionRoleArn
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref LambdaCodeKey
      Runtime: "nodejs20.x"

  LambdaFunction2:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: !Ref LambdaFunctionName2
      Handler: "index.handler"
      Role: !Ref LambdaExecutionRoleArn
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref LambdaCodeKey
      Runtime: "nodejs20.x"

  LambdaFunction3:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: !Ref LambdaFunctionName3
      Handler: "index.handler"
      Role: !Ref LambdaExecutionRoleArn
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref LambdaCodeKey
      Runtime: "nodejs20.x"

Outputs:
  LambdaFunction1Arn:
    Type: AWS::Serverless::Application
    Description: "ARN of the first Lambda function"
    Value: !GetAtt LambdaFunction1.Arn
    Export:
      Name: "LambdaFunction1Arn"

  LambdaFunction2Arn:
    Description: "ARN of the second Lambda function"
    Value: !GetAtt LambdaFunction2.Arn
    Export:
      Name: "LambdaFunction2Arn"

  LambdaFunction3Arn:
    Description: "ARN of the third Lambda function"
    Value: !GetAtt LambdaFunction3.Arn
    Export:
      Name: "LambdaFunction3Arn"