AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  LambdaCodeBucket:
    Type: String
    Description: "S3 bucket where Lambda code is stored"

  LambdaCodeKey:
    Type: String
    Description: "S3 key where Lambda code is stored"

  LambdaExecutionRoleArn:
    Type: String
    Description: "ARN of the IAM role that Lambda functions will use"

  LambdaFunctionName:
    Type: String
    Description: "The name of the first Lambda function"

Resources:
  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Handler: "index.handler"
      Role: !Ref LambdaExecutionRoleArn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      Runtime: "nodejs20.x"
      Events:
        WeeklyTrigger:
          Type: Schedule
          Properties:
            Schedule: "rate(7 days)"

Outputs:
  LambdaFunctionArn:
    Description: "ARN of the first Lambda function"
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: "LambdaFunctionArn"