AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Handler: 'index.handler'
      Role: !Ref LambdaExecutionRoleArn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      Runtime: 'nodejs14.x'

Parameters:
  LambdaFunctionName:
    Type: String
    Description: 'The name of the Lambda function.'

  LambdaCodeBucket:
    Type: String
    Description: 'The S3 bucket containing the Lambda code.'

  LambdaCodeKey:
    Type: String
    Description: 'The S3 key of the Lambda code.'

  LambdaExecutionRoleArn:
    Type: String
    Description: 'The ARN of the Lambda execution role.'
