AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Handler: 'index.handler'
      Role: !ImportValue LambdaExecutionRoleArn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      Runtime: 'nodejs14.x'

Outputs:
  FunctionArn:
    Description: 'The ARN of the Lambda function'
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: LambdaFunctionArn

Parameters:
  LambdaFunctionName:
    Type: String
    Description: The name of the Lambda function
    Default: demo-lambda-function
  LambdaCodeBucket:
    Type: String
    Description: The name of the S3 bucket containing the Lambda function code
    Default: demo-s3-bucket-lambda
  LambdaCodeKey:
    Type: String
    Description: The key of the Lambda function code in the S3 bucket
    Default: lambda-code.zip
