AWSTemplateFormatVersion: "2010-09-09"

Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "10.0.0.0/16"
      Tags:
        - Key: "Name"
          Value: !Ref VPCName

  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref S3BucketNameCreate
      AccessControl: !Ref AccessControl
      VersioningConfiguration:
        Status: !Ref VersioningStatus

Outputs:
  VPCId:
    Description: "The ID of the VPC"
    Value: !Ref VPC
    Export:
      Name: "VPCId"

  BucketName:
    Description: "The name of the S3 bucket"
    Value: !Ref S3Bucket
    Export:
      Name: "BucketName"

Parameters:
  VPCName:
    Type: String
    Description: The name of the VPC
    Default: demo-vpc

  S3BucketNameCreate:
    Type: String
    Description: The name of the S3 bucket
    Default: demo-s3-bucket

  AccessControl:
    Type: String
    Description: The access control for the S3 bucket
    Default: Private
    AllowedValues:
      - Private
      - PublicRead

  VersioningStatus:
    Type: String
    Description: The versioning status for the S3 bucket
    Default: Enabled
    AllowedValues:
      - Enabled
      - Suspended
