AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Main CloudFormation stack that includes VPC, EC2, S3, and Lambda resources.

Parameters:
  VPCName:
    Type: String
    Description: Name for the VPC
  LambdaFunctionName1:
    Type: String
    Description: Name for the first Lambda function
  LambdaFunctionName2:
    Type: String
    Description: Name for the second Lambda function
  LambdaFunctionName3:
    Type: String
    Description: Name for the third Lambda function
  LambdaCodeBucket1:
    Type: String
    Description: S3 bucket for Lambda function code
  LambdaCodeBucket2:
    Type: String
    Description: S3 bucket for Lambda function code
  LambdaCodeBucket3:
    Type: String
    Description: S3 bucket for Lambda function code
  LambdaCodeKey:
    Type: String
    Description: S3 key for Lambda function code
  EC2InstanceName:
    Type: String
    Description: Name for the EC2 instance
  S3BucketNameCreate:
    Type: String
    Description: Name for the S3 bucket to create
  S3BucketName:
    Type: String
    Description: Name for the S3 bucket to create
    Default: my-demo-s3-bucket-test-project-18
  Environment:
    Type: String
    Description: Environment (e.g., dev, prod)
  AccessControl:
    Type: String
    Description: S3 bucket access control
  VersioningStatus:
    Type: String
    Description: S3 bucket versioning status

Resources:

  NestedVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/vpc.yaml'
      Parameters:
        VPCName: !Ref VPCName

  NestedEC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/ec2.yaml'
      Parameters:
        EC2InstanceName: !Ref EC2InstanceName
    DependsOn: 
      - NestedVPCStack

  NestedIAMRoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/iam-role.yaml'

  NestedLambdaFunction1Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/lambda.yaml'
      Parameters:
        LambdaCodeBucket: !Ref LambdaCodeBucket1
        LambdaCodeKey: !Ref LambdaCodeKey
        LambdaExecutionRoleArn: !GetAtt NestedIAMRoleStack.Outputs.LambdaExecutionRoleArn
        LambdaFunctionName1: !Ref LambdaFunctionName1
    DependsOn: 
      - NestedIAMRoleStack

  NestedLambdaFunction2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/lambda.yaml'
      Parameters:
        LambdaCodeBucket: !Ref LambdaCodeBucket2
        LambdaCodeKey: !Ref LambdaCodeKey
        LambdaExecutionRoleArn: !GetAtt NestedIAMRoleStack.Outputs.LambdaExecutionRoleArn
        LambdaFunctionName2: !Ref LambdaFunctionName2
    DependsOn: 
      - NestedIAMRoleStack

  NestedLambdaFunction3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/lambda.yaml'
      Parameters:
        LambdaCodeBucket: !Ref LambdaCodeBucket3
        LambdaCodeKey: !Ref LambdaCodeKey
        LambdaExecutionRoleArn: !GetAtt NestedIAMRoleStack.Outputs.LambdaExecutionRoleArn
        LambdaFunctionName3: !Ref LambdaFunctionName3
    DependsOn: 
      - NestedIAMRoleStack
      - NestedS3BucketName

  NestedS3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/s3.yaml'
      Parameters:
        S3BucketName: !Ref S3BucketName
        AccessControl: !Ref AccessControl
        VersioningStatus: !Ref VersioningStatus

Outputs:
  VPCId:
    Description: "VPC ID"
    Value: !GetAtt NestedVPCStack.Outputs.VPCId

  S3BucketName:
    Description: "S3BucketName"
    Value: !GetAtt NestedVPCStack.Outputs.S3BucketName

  EC2InstanceId:
    Description: "EC2 Instance ID"
    Value: !GetAtt NestedEC2Stack.Outputs.EC2InstanceId

  LambdaFunctionArn1:
    Description: "Lambda Function ARN 1"
    Value: !GetAtt NestedLambdaFunction1Stack.Outputs.LambdaFunctionArn

  LambdaFunctionArn2:
    Description: "Lambda Function ARN 2"
    Value: !GetAtt NestedLambdaFunction2Stack.Outputs.LambdaFunctionArn

  LambdaFunctionArn3:
    Description: "Lambda Function ARN 3"
    Value: !GetAtt NestedLambdaFunction3Stack.Outputs.LambdaFunctionArn
