AWSTemplateFormatVersion: "2010-09-09"

Resources:
  NestedIAMRoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/iam-role.yaml'

  NestedVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/vpc.yaml'
      Parameters:
        VPCName: !Ref VPCName

  NestedS3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/s3.yaml'
      Parameters:
        S3BucketName: !Ref S3BucketName
        AccessControl: !Ref AccessControl
        VersioningStatus: !Ref VersioningStatus

  NestedEC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/ec2.yaml'
      Parameters:
        EC2InstanceName: !Ref EC2InstanceName

  NestedLambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
         - "NestedIAMRoleStack"
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/lambda.yaml'
      Parameters:
        LambdaCodeBucket: !Ref LambdaCodeBucket
        LambdaCodeKey: !Ref LambdaCodeKey
        LambdaExecutionRoleArn: !GetAtt NestedIAMRoleStack.Outputs.LambdaExecutionRoleArn
        LambdaFunctionName1: !Ref LambdaFunctionName1
        LambdaFunctionName2: !Ref LambdaFunctionName2
        LambdaFunctionName3: !Ref LambdaFunctionName3

Outputs:
  VPCId:
    Description: "The ID of the VPC"
    Value: !GetAtt NestedVPCStack.Outputs.VPCId
    Export:
      Name: !Sub "${AWS::StackName}-VPCId"

  BucketName:
    Description: "The name of the S3 bucket"
    Value: !GetAtt NestedS3Stack.Outputs.BucketName
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"

  InstanceId:
    Description: "The ID of the EC2 instance"
    Value: !GetAtt NestedEC2Stack.Outputs.InstanceId
    Export:
      Name: !Sub "${AWS::StackName}-InstanceId"

  LambdaExecutionRoleArn:
    Description: "ARN of the Lambda execution role"
    Value: !GetAtt NestedIAMRoleStack.Outputs.LambdaExecutionRoleArn
    Export:
      Name: !Sub "${AWS::StackName}-LambdaExecutionRoleArn"

  LambdaFunction1Arn:
    Description: "ARN of the first Lambda function"
    Value: !GetAtt NestedLambdaStack.Outputs.LambdaFunction1Arn
  Export:
    Name: !Sub "${AWS::StackName}-LambdaFunction1Arn"

  LambdaFunction2Arn:
    Description: "ARN of the second Lambda function"
    Value: !GetAtt NestedLambdaStack.Outputs.LambdaFunction2Arn
    Export:
      Name: !Sub "${AWS::StackName}-LambdaFunction2Arn"

  LambdaFunction3Arn:
    Description: "ARN of the third Lambda function"
    Value: !GetAtt NestedLambdaStack.Outputs.LambdaFunction3Arn
    Export:
     Name: !Sub "${AWS::StackName}-LambdaFunction3Arn"

Parameters:
  VPCName:
    Type: String
    Description: The name of the VPC
    Default: demo-vpc

  S3BucketName:
    Type: String
    Description: The name of the S3 bucket
    Default: my-demo-s3-bucket-test-project-18

  AccessControl:
    Type: String
    Description: The access control for the S3 bucket
    Default: Private
    AllowedValues:
      - Private
      - PublicRead

  VersioningStatus:
    Type: String
    Description: The versioning status for the S3 bucket
    Default: Enabled
    AllowedValues:
      - Enabled
      - Suspended

  EC2InstanceName:
    Type: String
    Description: The name of the EC2 instance
    Default: demo-ec2-instance

  LambdaCodeBucket:
    Type: String
    Description: "S3 bucket where Lambda code is stored"
    Default: my-demo-s3-bucket-test-project-11

  LambdaCodeKey:
    Type: String
    Description: "S3 key where Lambda code is stored"
    Default: lambda-code.zip

  LambdaFunctionName1:
    Type: String
    Description: The name of the first Lambda function
    Default: demo-lambda-function-1

  LambdaFunctionName2:
    Type: String
    Description: The name of the second Lambda function
    Default: demo-lambda-function-2

  LambdaFunctionName3:
    Type: String
    Description: The name of the third Lambda function
    Default: demo-lambda-function-3
