AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack template

Parameters:
  VPCName:
    Type: String
    Description: The name of the VPC

  EC2InstanceName:
    Type: String
    Description: The name of the EC2 instance

  S3BucketNameCreate:
    Type: String
    Description: The name of the S3 bucket to be created

  Environment:
    Type: String
    Description: The environment name
    Default: dev
    AllowedValues: [dev, prod]

  AccessControl:
    Type: String
    Description: The access control for the S3 bucket
    Default: Private
    AllowedValues: [Private, PublicRead, PublicReadWrite, AuthenticatedRead]

  VersioningStatus:
    Type: String
    Description: The versioning status for the S3 bucket
    Default: Enabled
    AllowedValues: [Enabled, Suspended]

Resources:
  NestedIAMRoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/iam-role.yaml'

  NestedVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/vpc.yaml'
      Parameters:
        VPCName: !Ref VPCName

  NestedS3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/s3.yaml'
      Parameters:
        S3BucketName: !Ref S3BucketName
        AccessControl: !Ref AccessControl
        VersioningStatus: !Ref VersioningStatus

  NestedEC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/ec2.yaml'
      Parameters:
        EC2InstanceName: !Ref EC2InstanceName

Outputs:
  VPCId:
    Description: "The ID of the VPC"
    Value: !GetAtt NestedVPCStack.Outputs.VPCId
    Export:
      Name: !Sub "${AWS::StackName}-VPCId"

  BucketName:
    Description: "The name of the S3 bucket"
    Value: !GetAtt NestedS3Stack.Outputs.BucketName
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"

  InstanceId:
    Description: "The ID of the EC2 instance"
    Value: !GetAtt NestedEC2Stack.Outputs.InstanceId
    Export:
      Name: !Sub "${AWS::StackName}-InstanceId"