AWSTemplateFormatVersion: "2010-09-09"

Resources:
  # Create the IAM Role Stack first
  NestedIAMRoleStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - NestedVPCStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/iam-role.yaml'

  # Create the VPC Stack
  NestedVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/vpc.yaml'
      Parameters:
        VPCName: !Ref VPCName

  # Create the EC2 Stack
  NestedEC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - NestedIAMRoleStack
      - NestedVPCStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/ec2.yaml'
      Parameters:
        EC2InstanceName: !Ref EC2InstanceName

  # Create the Lambda Stack
  NestedLambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - NestedIAMRoleStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/lambda.yaml'
      Parameters:
        LambdaCodeBucket: my-demo-s3-bucket-test-project-11
        LambdaCodeKey: lambda-code.zip
        LambdaExecutionRoleArn: !GetAtt NestedIAMRoleStack.Outputs.LambdaExecutionRoleArn
        LambdaFunctionName1: !Ref LambdaFunctionName1
        LambdaFunctionName2: !Ref LambdaFunctionName2
        LambdaFunctionName3: !Ref LambdaFunctionName3

Outputs:
  VPCId:
    Description: "The ID of the VPC"
    Value: !GetAtt NestedVPCStack.Outputs.VPCId
    Export:
      Name: !Sub "${AWS::StackName}-VPCId"

  InstanceId:
    Description: "The ID of the EC2 instance"
    Value: !GetAtt NestedEC2Stack.Outputs.InstanceId
    Export:
      Name: !Sub "${AWS::StackName}-InstanceId"

Parameters:
  VPCName:
    Type: String
    Description: The name of the VPC
    Default: demo-vpc

  AccessControl:
    Type: String
    Description: The access control for the S3 bucket
    Default: Private
    AllowedValues:
      - Private
      - PublicRead

  VersioningStatus:
    Type: String
    Description: The versioning status for the S3 bucket
    Default: Enabled
    AllowedValues:
      - Enabled
      - Suspended

  EC2InstanceName:
    Type: String
    Description: The name of the EC2 instance
    Default: demo-ec2-instance

  LambdaFunctionName1:
    Type: String
    Description: The name of the first Lambda function
    Default: demo-lambda-function-1

  LambdaFunctionName2:
    Type: String
    Description: The name of the second Lambda function
    Default: demo-lambda-function-2

  LambdaFunctionName3:
    Type: String
    Description: The name of the third Lambda function
    Default: demo-lambda-function-3
