AWSTemplateFormatVersion: '2010-09-09'
Resources:

  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://${S3BucketNameCreate}.s3.amazonaws.com/vpc.yaml'
      Parameters:
        VPCName: !Ref VPCName

  S3Stack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://${S3BucketNameCreate}.s3.amazonaws.com/s3.yaml'
      Parameters:
        S3BucketName: !Ref S3BucketName

  EC2Stack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://${S3BucketNameCreate}.s3.amazonaws.com/ec2.yaml'
      Parameters:
        EC2InstanceName: !Ref EC2InstanceName

Parameters:
  VPCName:
    Type: String
    Default: my-demo-vpc

  S3BucketName:
    Type: String
    Default: my-demo-s3-bucket

  EC2InstanceName:
    Type: String
    Default: my-demo-ec2

  S3BucketNameCreate:
    Type: String
    Default: my-demo-cloudformation-bucket

Outputs:
  MyS3BucketName:
    Description: "S3 Bucket created for CloudFormation templates"
    Value: !Ref S3BucketNameCreate
