AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName

Outputs:
  BucketName:
    Description: 'The name of the S3 bucket'
    Value: !Ref S3Bucket
