Description: VPC Nested Stack Creation
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  MyVpcBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: VPC CIDR Range
  
  MySubnetNS1Block:
    Type: String
    Default: 10.0.1.0/24
    Description: CIDR Block for SubnetNS1 Within The VPC

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Dev VPC Network Configuration
        Parameters:
          - MyVpcBlock
          - MySubnetNS1Block
    Parameters:
      MyVpcBlock:
        Label:
          default: VPC CIDR Range Selection

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref MyVpcBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-myVPC"

  SubnetNS1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: !Ref MySubnetNS1Block
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-SubnetNS1"
      AvailabilityZone: 
        Fn::Select:
          - '0'
          - Fn::GetAZs:
              Ref: AWS::Region

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: Public Subnet
        - Key: Network
          Value: Public

  SubnetNS1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref SubnetNS1

  InternetGateway:
    Type: AWS::EC2::InternetGateway
  
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref myVPC

  Route: 
    DependsOn: VPCGatewayAttachment
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

Outputs:
  SubnetNS1Id:
    Value: !Ref SubnetNS1
    Export:
      Name: !Sub "${AWS::StackName}-SubnetNS1Id"

  VpcId:
    Value: !Ref myVPC
    Export:
      Name: !Sub "${AWS::StackName}-VpcId"
