AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  VPCName:
    Type: String
    Description: The name of the VPC
    Default: demo-vpc
    
Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "10.0.0.0/16"
      Tags:
        - Key: "Name"
          Value: !Ref VPCName

Outputs:
  VPCId:
    Description: "The ID of the VPC"
    Value: !Ref VPC
    Export:
      Name: "VPCId"

