AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref VPCName

Outputs:
  VPCId:
    Description: 'The ID of the VPC'
    Value: !Ref VPC

Parameters:
  VPCName:
    Type: String
    Description: "The name of the VPC."
    Default: my-demo-vpc
