name: Deploy AWS Resources using GitHub Actions

on:
  workflow_dispatch:
  push:
    branches:
      - Dev

jobs:
  cloudformation-deploy:
    name: Deploy CloudFormation
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@master

      - name: Set environment variables
        id: set-env
        run: |
          BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          if [[ $BRANCH == 'master' || $BRANCH == 'main' ]]; then
            echo "DEPLOYMENT_ENV=prod" >> $GITHUB_ENV
            echo "DEPLOYMENT_ROLE_ARN=${{ secrets.PROD_DEPLOYMENT_ROLE }}" >> $GITHUB_ENV
            echo "S3_BUCKET=${{ secrets.PROD_S3_BUCKET }}" >> $GITHUB_ENV
            echo "STACK_NAME=main-stack-prod" >> $GITHUB_ENV
          elif [[ $BRANCH == 'qa' ]]; then
            echo "DEPLOYMENT_ENV=qa" >> $GITHUB_ENV
            echo "DEPLOYMENT_ROLE_ARN=${{ secrets.QA_DEPLOYMENT_ROLE }}" >> $GITHUB_ENV
            echo "S3_BUCKET=${{ secrets.QA_S3_BUCKET }}" >> $GITHUB_ENV
            echo "STACK_NAME=main-stack-qa" >> $GITHUB_ENV
          else
            echo "DEPLOYMENT_ENV=dev" >> $GITHUB_ENV
            echo "DEPLOYMENT_ROLE_ARN=${{ secrets.DEV_DEPLOYMENT_ROLE }}" >> $GITHUB_ENV
            echo "S3_BUCKET=${{ secrets.DEV_S3_BUCKET }}" >> $GITHUB_ENV
            echo "STACK_NAME=main-stack-dev" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload nested stack templates to S3
        run: |
          aws s3 cp ./Resources/vpc.yaml s3://${{ env.S3_BUCKET }}/vpc.yaml
          aws s3 cp ./Resources/s3.yaml s3://${{ env.S3_BUCKET }}/s3.yaml
          aws s3 cp ./Resources/iam-role.yaml s3://${{ env.S3_BUCKET }}/iam-role.yaml
          aws s3 cp ./Resources/parameters-${{ env.DEPLOYMENT_ENV }}.json s3://${{ env.S3_BUCKET }}/parameters-${{ env.DEPLOYMENT_ENV }}.json

      - name: Print environment variables
        run: |
          echo "Role ARN: ${{ env.DEPLOYMENT_ROLE_ARN }}"
          echo "Deployment Environment: ${{ env.DEPLOYMENT_ENV }}"
          echo "S3 Bucket: ${{ env.S3_BUCKET }}"
          echo "Stack Name: ${{ env.STACK_NAME }}"

      - name: Run AWS CloudFormation Linter
        uses: ScottBrenner/cfn-lint-action@v2.3.1

      - name: Deploy CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.STACK_NAME }}
          template: ./Resources/main.yaml
          parameter-overrides: file://${{ github.workspace }}/Resources/parameters-${{ env.DEPLOYMENT_ENV }}.json
          capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"

      - name: Get CloudFormation Outputs
        id: get_outputs
        run: |
          outputs=$(aws cloudformation describe-stacks --stack-name ${{ env.STACK_NAME }} --query "Stacks[0].Outputs" --output json)
          echo "outputs=$(echo $outputs | jq -c .)" >> $GITHUB_ENV

      - name: Parse and Set Outputs
        run: |
          VPC_ID=$(echo $outputs | jq -r '.[] | select(.OutputKey=="VPCId") | .OutputValue')
          INSTANCE_ID=$(echo $outputs | jq -r '.[] | select(.OutputKey=="InstanceId") | .OutputValue')
          BUCKET_NAME=$(echo $outputs | jq -r '.[] | select(.OutputKey=="BucketName") | .OutputValue')
          echo "VPC_ID=$VPC_ID" >> $GITHUB_ENV
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

      - name: Save VPC ID as artifact
        run: echo ${{ env.VPC_ID }} > vpc-id.txt

      - name: Upload VPC ID artifact
        uses: actions/upload-artifact@v3
        with:
          name: vpc-id
          path: vpc-id.txt

      - name: Save S3 Bucket Name as artifact
        run: echo ${{ env.BUCKET_NAME }} > s3-bucket-name.txt

      - name: Upload S3 Bucket Name artifact
        uses: actions/upload-artifact@v3
        with:
          name: s3-bucket-name
          path: s3-bucket-name.txt
