name: Deploy AWS Resources

on:
  push:
    branches:
      - Dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: my-demo-s3-bucket-test-project-18
      EC2_INSTANCE_NAME: my-demo-ec2-instance

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Check if S3 stack is in ROLLBACK_COMPLETE state
      id: check_s3_stack
      run: |
        STACK_STATUS=$(aws cloudformation describe-stacks --stack-name create-s3-bucket-stack --query "Stacks[0].StackStatus" --output text || echo "STACK_NOT_FOUND")
        echo "::set-output name=stack_status::$STACK_STATUS"

    - name: Delete S3 stack if in ROLLBACK_COMPLETE state
      if: steps.check_s3_stack.outputs.stack_status == 'ROLLBACK_COMPLETE'
      run: |
        aws cloudformation delete-stack --stack-name create-s3-bucket-stack
        aws cloudformation wait stack-delete-complete --stack-name create-s3-bucket-stack

    - name: Deploy S3 Bucket Stack
      run: |
        aws cloudformation deploy \
          --template-file Resources/create-s3-bucket.yaml \
          --stack-name create-s3-bucket-stack \
          --parameter-overrides BucketName=${{ env.S3_BUCKET_NAME }} \
          --capabilities CAPABILITY_NAMED_IAM

    - name: Verify S3 Bucket Creation
      run: |
        aws s3 ls s3://${{ env.S3_BUCKET_NAME }} || echo "Bucket does not exist or access denied"

    - name: Check if EC2 stack is in ROLLBACK_COMPLETE state
      id: check_ec2_stack
      run: |
        STACK_STATUS=$(aws cloudformation describe-stacks --stack-name create-ec2-instance-stack --query "Stacks[0].StackStatus" --output text || echo "STACK_NOT_FOUND")
        echo "::set-output name=stack_status::$STACK_STATUS"

    - name: Delete EC2 stack if in ROLLBACK_COMPLETE state
      if: steps.check_ec2_stack.outputs.stack_status == 'ROLLBACK_COMPLETE'
      run: |
        aws cloudformation delete-stack --stack-name create-ec2-instance-stack
        aws cloudformation wait stack-delete-complete --stack-name create-ec2-instance-stack

    - name: Deploy EC2 Instance Stack
      run: |
        aws cloudformation deploy \
          --template-file Resources/ec2.yaml \
          --stack-name create-ec2-instance-stack \
          --parameter-overrides EC2InstanceName=${{ env.EC2_INSTANCE_NAME }} \
          --capabilities CAPABILITY_NAMED_IAM

    - name: Verify EC2 Instance Creation
      run: |
        aws ec2 describe-instances --filters "Name=tag:Name,Values=${{ env.EC2_INSTANCE_NAME }}" --query "Reservations[*].Instances[*].InstanceId" --output text || echo "Instance does not exist or access denied"
